"""Report Renderer 模块单元测试。"""

from __future__ import annotations

import json

from ai_pr_review.config import ReportRendererConfig
from ai_pr_review.models.pr_data import FileDiff, FileStatus, PRData
from ai_pr_review.services.prompt_assembler import Finding, ReviewResult
from ai_pr_review.services.report_renderer import ReportRenderer


def build_pr_data() -> PRData:
    return PRData(
        pr_number=123,
        title="Add user authentication",
        description="desc",
        author="alice",
        state="open",
        head_sha="head123",
        base_sha="base123",
        head_ref="feature/auth",
        base_ref="main",
        diff="diff --git a/src/services/user.py b/src/services/user.py",
        files=[
            FileDiff(
                filename="src/services/user.py",
                status=FileStatus.MODIFIED,
                additions=10,
                deletions=2,
                changes=12,
                patch="@@ -45,2 +45,2 @@",
            )
        ],
        url="https://github.com/owner/repo/pull/123",
        merged=False,
        owner="owner",
        repo="repo",
    )


def build_review_result() -> ReviewResult:
    return ReviewResult(
        summary="Potential security and reliability issues found.",
        findings=[
            Finding(
                severity="critical",
                category="security",
                file="src/services/user.py",
                line_start=45,
                line_end=52,
                title="SQL Injection in user query",
                problem="User input is directly concatenated into SQL query.",
                suggestion="Use parameterized query instead of f-string.",
                confidence=0.95,
                code_snippet='query = f"SELECT * FROM users WHERE id = {user_id}"',
            ),
            Finding(
                severity="high",
                category="error_handling",
                file="src/services/user.py",
                line_start=23,
                line_end=28,
                title="Missing error handling",
                problem="The database call can raise without being handled.",
                suggestion="Wrap the call and convert failures into a safe response.",
                confidence=0.88,
                code_snippet="await db.fetch_one(query)",
            ),
        ],
    )


def test_render_terminal_outputs_summary_and_findings():
    renderer = ReportRenderer()

    output = renderer.render_terminal(build_review_result(), build_pr_data())

    assert "AI PR Review Report" in output
    assert "PR: #123 - Add user authentication" in output
    assert "Total Findings: 2" in output
    assert "Critical: 1" in output
    assert "High: 1" in output
    assert "SQL Injection in user query" in output
    assert "Missing error handling" in output


def test_render_markdown_outputs_expected_sections():
    renderer = ReportRenderer()

    output = renderer.render_markdown(build_review_result(), build_pr_data())

    assert "# AI PR Review Report" in output
    assert "## Summary" in output
    assert "- **PR**: #123 - Add user authentication" in output
    assert "## Critical Findings" in output
    assert "### SQL Injection in user query" in output
    assert "- **Severity**: Critical" in output
    assert "```python" in output
    assert "**Suggestion**: Use parameterized query instead of f-string." in output


def test_render_json_outputs_structured_payload():
    renderer = ReportRenderer()

    output = renderer.render_json(build_review_result(), build_pr_data())
    payload = json.loads(output)

    assert payload["pr"]["number"] == 123
    assert payload["pr"]["repository"] == "owner/repo"
    assert payload["counts"]["total_findings"] == 2
    assert payload["counts"]["by_severity"]["critical"] == 1
    assert payload["findings"][0]["title"] == "SQL Injection in user query"


def test_render_github_comment_outputs_summary_table_and_footer():
    renderer = ReportRenderer()

    output = renderer.render_github_comment(build_review_result(), build_pr_data())

    assert "## 🤖 AI PR Review Report" in output
    assert "| Files Changed | 1 |" in output
    assert "### Critical Findings" in output
    assert "#### ❌ SQL Injection in user query" in output
    assert "*Generated by AI PR Review Assistant*" in output
    assert "```python" not in output


def test_render_markdown_supports_custom_template():
    renderer = ReportRenderer(
        ReportRendererConfig(
            markdown_template="# {title}\n\nPR: #{pr_number}\n\n{findings_markdown}"
        )
    )

    output = renderer.render_markdown(build_review_result(), build_pr_data())

    assert output.startswith("# AI PR Review Report")
    assert "PR: #123" in output
    assert "## Critical Findings" in output


def test_render_github_comment_can_include_code_snippets_when_enabled():
    renderer = ReportRenderer(ReportRendererConfig(include_code_snippets_in_github_comment=True))

    output = renderer.render_github_comment(build_review_result(), build_pr_data())

    assert "```python" in output
    assert 'query = f"SELECT * FROM users WHERE id = {user_id}"' in output
