"""Report Renderer 模块单元测试。"""

from __future__ import annotations

import json

from ai_pr_review.config import ReportRendererConfig
from ai_pr_review.models.pr_data import FileDiff, FileStatus, PRData
from ai_pr_review.services.prompt_assembler import Finding, ReviewResult
from ai_pr_review.services.report_renderer import GitHubCommentMeta, ReportRenderer


def build_pr_data() -> PRData:
    return PRData(
        pr_number=123,
        title="Add user authentication",
        description="desc",
        author="alice",
        state="open",
        head_sha="head123",
        base_sha="base123",
        head_ref="feature/auth",
        base_ref="main",
        diff="diff --git a/src/services/user.py b/src/services/user.py",
        files=[
            FileDiff(
                filename="src/services/user.py",
                status=FileStatus.MODIFIED,
                additions=10,
                deletions=2,
                changes=12,
                patch="@@ -45,2 +45,2 @@",
            )
        ],
        url="https://github.com/owner/repo/pull/123",
        merged=False,
        owner="owner",
        repo="repo",
    )


def build_review_result() -> ReviewResult:
    return ReviewResult(
        summary="Potential security and reliability issues found.",
        findings=[
            Finding(
                severity="critical",
                category="security",
                file="src/services/user.py",
                line_start=45,
                line_end=52,
                title="SQL Injection in user query",
                problem="User input is directly concatenated into SQL query.",
                suggestion="Use parameterized query instead of f-string.",
                confidence=0.95,
                code_snippet='query = f"SELECT * FROM users WHERE id = {user_id}"',
            ),
            Finding(
                severity="high",
                category="error_handling",
                file="src/services/user.py",
                line_start=23,
                line_end=28,
                title="Missing error handling",
                problem="The database call can raise without being handled.",
                suggestion="Wrap the call and convert failures into a safe response.",
                confidence=0.88,
                code_snippet="await db.fetch_one(query)",
            ),
        ],
    )


def test_render_terminal_outputs_summary_and_findings():
    renderer = ReportRenderer()

    output = renderer.render_terminal(build_review_result(), build_pr_data())

    assert "AI PR Review Report" in output
    assert "PR: #123 - Add user authentication" in output
    assert "Total Findings: 2" in output
    assert "Critical: 1" in output
    assert "High: 1" in output
    assert "SQL Injection in user query" in output
    assert "Missing error handling" in output


def test_render_markdown_outputs_expected_sections():
    renderer = ReportRenderer()

    output = renderer.render_markdown(build_review_result(), build_pr_data())

    assert "# AI PR Review Report" in output
    assert "## Summary" in output
    assert "- **PR**: #123 - Add user authentication" in output
    assert "## Critical Findings" in output
    assert "### SQL Injection in user query" in output
    assert "- **Severity**: Critical" in output
    assert "```python" in output
    assert "**Suggestion**: Use parameterized query instead of f-string." in output


def test_render_json_outputs_structured_payload():
    renderer = ReportRenderer()

    output = renderer.render_json(build_review_result(), build_pr_data())
    payload = json.loads(output)

    assert payload["pr"]["number"] == 123
    assert payload["pr"]["repository"] == "owner/repo"
    assert payload["counts"]["total_findings"] == 2
    assert payload["counts"]["by_severity"]["critical"] == 1
    assert payload["findings"][0]["title"] == "SQL Injection in user query"


def test_render_github_comment_outputs_target_stats_and_footer():
    renderer = ReportRenderer()

    output = renderer.render_github_comment(build_review_result(), build_pr_data())

    assert "## 🤖 AI PR Review Report" in output
    assert (
        "**`owner/repo`** · [PR #123](https://github.com/owner/repo/pull/123) · "
        "Add user authentication · @alice · 1 files changed"
    ) in output
    assert "> **2 findings** · 🛑 1 critical · ⚠️ 1 high" in output
    assert "**evidence (location + snippet)**" in output
    assert "### 🎯 Fix first (top 2)" in output
    assert "<summary><b>🛑 Critical · 1</b></summary>" in output
    assert "#### 1. 🛑 SQL Injection in user query" in output
    assert "*Generated by AI PR Review Assistant*" in output
    assert "```python" not in output


def test_render_github_comment_links_lines_and_needs_metadata_for_it():
    """`file:line` becomes a blob link only when the commit is known."""
    without_sha = ReportRenderer().render_github_comment(build_review_result(), build_pr_data())
    assert "https://github.com/owner/repo/blob/" not in without_sha
    assert "`src/services/user.py:45-52`" in without_sha

    with_sha = ReportRenderer().render_github_comment(
        build_review_result(),
        build_pr_data(),
        meta=GitHubCommentMeta(head_sha="head123", run_id="run-12345678", model="deepseek-flash"),
    )
    assert (
        "[`src/services/user.py:45-52`]"
        "(https://github.com/owner/repo/blob/head123/src/services/user.py#L45-L52)"
    ) in with_sha
    assert "模型 `deepseek-flash`" not in with_sha  # default language is English
    assert "model `deepseek-flash` · run `run-1234`" in with_sha


def test_render_github_comment_localizes_for_chinese():
    output = ReportRenderer().render_github_comment(
        build_review_result(),
        build_pr_data(),
        meta=GitHubCommentMeta(language="zh-CN", head_sha="head123", run_id="run-12345678"),
    )

    assert "## 🤖 AI PR 审查报告" in output
    assert "个变更文件" in output
    assert "> **2 个问题** · 🛑 1 严重 · ⚠️ 1 高" in output
    assert "证据校验（位置与片段自洽）" in output
    assert "❔ 未校验 2" in output
    assert "### 🎯 优先修复（Top 2）" in output
    assert "<summary><b>🛑 严重 · 1 条</b></summary>" in output
    assert "置信度 95%" in output
    assert "**问题**：" in output and "**建议**：" in output
    assert "<sub>证据优先 · 位置与片段校验通过 0/2" in output


def test_render_github_comment_folds_per_file_summary_and_long_details():
    result = build_review_result()
    result.summary = (
        "整体结论：两处问题需要修复。\n"
        "src/a.py: 文件 A 的结论。\n"
        "src/b.py: 文件 B 的结论。"
    )
    result.findings[0].problem = "P" * 400
    result.findings[0].suggestion = "S" * 20

    output = ReportRenderer().render_github_comment(result, build_pr_data())

    assert "### 📌 Review summary" in output
    assert "整体结论：两处问题需要修复。" in output
    assert "<summary><b>📄 Model summary by file (2 files)</b></summary>" in output
    assert "**`src/a.py`**" in output and "**`src/b.py`**" in output
    # The 400-char problem is folded instead of flooding the scan path.
    assert "<summary>Problem / Suggestion</summary>" in output


def test_render_github_comment_without_findings_is_short():
    result = build_review_result()
    result.findings = []

    output = ReportRenderer().render_github_comment(result, build_pr_data())

    assert "### ✅ No findings" in output
    assert "<details" not in output
    assert "Fix first" not in output


def test_render_github_comment_escapes_prose_so_github_keeps_it():
    """GitHub strips unknown tags: quoted evidence must survive verbatim."""
    result = build_review_result()
    finding = result.findings[0]
    finding.title = "Unescaped <script> in head"
    finding.problem = 'The template ends with </head> and uses target="_blank" without rel.'
    finding.suggestion = "# Wrap it"
    finding.evidence_issues = ["missing <meta> tag"]

    output = ReportRenderer().render_github_comment(result, build_pr_data())

    assert "&#96;" not in output
    assert "<script>" not in output
    assert "&lt;script&gt;" in output
    assert "&lt;/head&gt;" in output
    assert 'target="_blank"' in output  # quotes are safe; only angle brackets escaped
    assert "\\# Wrap it" in output
    assert "missing &lt;meta&gt; tag" in output


def test_render_github_comment_handles_backticks_in_paths():
    result = build_review_result()
    result.findings[0].file = "docs/we`ird name.md"

    output = ReportRenderer().render_github_comment(result, build_pr_data())

    assert "`` docs/we`ird name.md:45-52 ``" in output


def test_render_github_comment_falls_back_to_pr_files_for_forks():
    """A fork head commit is not in the base repo, so do not link the blob."""
    output = ReportRenderer().render_github_comment(
        build_review_result(),
        build_pr_data(),
        meta=GitHubCommentMeta(head_sha="fork-sha", from_fork=True),
    )

    assert "https://github.com/owner/repo/blob/fork-sha" not in output
    assert "https://github.com/owner/repo/pull/123/files" in output


def test_render_github_comment_reports_coverage_time_and_estimated_cost():
    output = ReportRenderer().render_github_comment(
        build_review_result(),
        build_pr_data(),
        meta=GitHubCommentMeta(
            language="zh-CN",
            head_sha="head123",
            run_id="run-12345678",
            model="deepseek-flash",
            reviewed_at="2026-09-20 09:12 UTC",
            files_reviewed=1,
            files_skipped=0,
            duration_seconds=66.1,
            cost=0.0021,
        ),
    )

    assert "已审查 1/1 个文件" in output
    assert "（跳过 0）" not in output
    pr_two_files = build_pr_data()
    pr_two_files.files = pr_two_files.files + [
        FileDiff(
            filename="src/services/other.py",
            status=FileStatus.MODIFIED,
            additions=1,
            deletions=1,
            changes=2,
            patch="@@ -1 +1 @@",
        )
    ]
    skipped = ReportRenderer().render_github_comment(
        build_review_result(),
        pr_two_files,
        meta=GitHubCommentMeta(language="zh-CN", files_reviewed=1, files_skipped=1),
    )
    assert "已审查 1/2 个文件（跳过 1）" in skipped
    assert "审查于 2026-09-20 09:12 UTC" in output
    assert "耗时 66.1s" in output
    assert "≈ $0.0021" in output

    unrecorded = ReportRenderer().render_github_comment(
        build_review_result(),
        build_pr_data(),
        meta=GitHubCommentMeta(language="zh-CN", cost=0.0),
    )
    assert "成本未记录" in unrecorded
    assert "$0.0000" not in unrecorded


def test_render_github_comment_caps_a_runaway_comment():
    result = build_review_result()
    template = result.findings[0]
    result.findings = []
    for index in range(120):
        clone = template.model_copy(deep=True)
        clone.title = f"Finding {index} " + "T" * 40
        clone.problem = "P" * 400
        clone.suggestion = "S" * 400
        result.findings.append(clone)

    output = ReportRenderer().render_github_comment(
        result,
        build_pr_data(),
        meta=GitHubCommentMeta(run_id="run-12345678", head_sha="head123"),
    )

    assert len(output) <= 24_000
    assert "per-file prose omitted" in output
    assert "more in this severity" in output
    # Every severity bucket past the visible ones is still accounted for.
    assert "120" not in output or "more in this severity" in output


def test_render_github_comment_fence_grows_past_snippet_backticks():
    result = build_review_result()
    result.findings[0].code_snippet = "print('```')\nmore\n```"

    output = ReportRenderer(
        ReportRendererConfig(include_code_snippets_in_github_comment=True)
    ).render_github_comment(result, build_pr_data())

    assert "````python" in output
    assert "````" in output.split("````python", 1)[1]


def test_render_github_comment_evidence_badges_do_not_overclaim():
    result = build_review_result()
    result.findings[0].evidence_status = "valid"
    result.findings[1].evidence_status = "needs_review"

    chinese = ReportRenderer().render_github_comment(
        result, build_pr_data(), meta=GitHubCommentMeta(language="zh-CN")
    )
    english = ReportRenderer().render_github_comment(result, build_pr_data())

    assert "✅ 校验通过" in chinese and "🔍 待人工确认" in chinese
    assert "证据有效" not in chinese
    assert "✅ validated" in english and "🔍 needs review" in english


def test_render_markdown_supports_custom_template():
    renderer = ReportRenderer(
        ReportRendererConfig(
            markdown_template="# {title}\n\nPR: #{pr_number}\n\n{findings_markdown}"
        )
    )

    output = renderer.render_markdown(build_review_result(), build_pr_data())

    assert output.startswith("# AI PR Review Report")
    assert "PR: #123" in output
    assert "## Critical Findings" in output


def test_render_github_comment_can_include_code_snippets_when_enabled():
    renderer = ReportRenderer(ReportRendererConfig(include_code_snippets_in_github_comment=True))

    output = renderer.render_github_comment(build_review_result(), build_pr_data())

    assert "```python" in output
    assert 'query = f"SELECT * FROM users WHERE id = {user_id}"' in output
